---
reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/open-balena-vpn
    - path: .
      dockerfile: Dockerfile.no-systemd
      docker_repo: balena/open-balena-vpn:no-systemd
