#!/usr/bin/env bash
set -ex

is_up() {
	local service="$1"
	local result
	result="$(s6-svstat "/run/service/${service}" -o up)"
	test "${result}" = "true"
}

is_up open-balena-vpn
is_up haproxy

curl -I --fail http://localhost/ping
