# https://github.com/zyedidia/eget#configuration
[global]
quiet = false
show_hash = true
upgrade_only = false
all = true

["prometheus/node_exporter"]
asset_filters = [".tar.gz"]
target = "/usr/local/bin"
file = "node_exporter"

["ncabatoff/process-exporter"]
asset_filters = [".tar.gz"]
target = "/usr/local/bin"
file = "process-exporter"

["natrontech/openvpn-exporter"]
asset_filters = [".tar.gz", "^.sbom.json"]
target = "/usr/local/bin"
file = "openvpn-exporter-linux-amd64"

["balena-io/sshproxy"]
asset_filters = [".tar.gz"]
target = "/usr/local/bin"
file = "*"
