#!/usr/bin/env bash

set -euo pipefail

# Redirect all future stdout/stderr to s6-log
exec > >(exec s6-log p"process-exporter[$$]:" 1 || true) 2>&1

exec /usr/local/bin/process-exporter \
    -web.listen-address 127.0.0.1:9001 \
    -web.telemetry-path /metrics/process \
    -procnames haproxy,node,openvpn
