name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  # allow external contributions to use secrets within trusted code
  pull_request_target:
    types: [opened, synchronize, closed]
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    # prevent duplicate workflow executions for pull_request and pull_request_target
    if: |
      (
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event_name == 'pull_request'
      ) || (
        github.event.pull_request.head.repo.full_name != github.repository &&
        github.event_name == 'pull_request_target'
      )
    secrets: inherit
    with:
      docker_images: balena/open-balena-vpn
      # ubuntu-20.04 (focal) avoids conflicts with systemd on the host
      runs_on: '["ubuntu-20.04"]'
      # actuated only has "focal" images for x86_64 right now
      docker_runs_on: >
        {
          "linux/amd64": ["self-hosted","focal"],
          "linux/arm64": ["self-hosted","distro:focal","ARM64"]
        }
